### ISSUE TITLE
Filetype theme not working

### ISSUE THREAD

**Issue by Areku-The-OF** [Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1#1]
I downloaded the [Windows 11 Theme by ivan13x](https://www.deviantart.com/ivan13x/art/Windows-11-Theme-885090687) but when I open the program it tells me that it can't load it because the filetype icon is incomplete or that the theme.ini file is missing. When I compared this theme with others everything is there, so I really don't know what seems to be the issue...

**Comment by ElemenTP** [comment]
I met the same issue too, but i figured out that rename sqfs.ico to squfs.ico will fix the issue.  
![issue](https://user-images.githubusercontent.com/57991536/140264280-2ede793f-4e02-4bd1-b755-3a30ad7b5185.png)

**Comment by Wilenty** [comment]
Okay guys, I will change the "squfs" to "sqfs", and I will add a info about it here.
BTW, if you want to add any Theme to existing themes, please link me to the files, because I don't have the accounts everywhere.

**Comment by Wilenty** [comment]
I renamed the "squfs" to "sqfs", so, please check it now.

BTW, the "Fluent" icons theme looks similar to the "Windows 11" icons theme:
![Fluent](https://user-images.githubusercontent.com/61757638/140283725-25c9972a-1363-4e87-a4c5-d2740d962ce9.png)
