### ISSUE TITLE
Hello thank you for update

### ISSUE THREAD

**Issue by EgeGurkan** [Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1#2]
I really liked this new version, please don't abondone it.

Can you also test for Windows 11 x64 Latest Build With 7Zip 21.5 Stable? Thank you very much sir.
Can u add check for updates to the software itself?

Also a bug report, when icon's folder is removed it gives error but says no filetype folder is found.... but actually its icons folder... it might give errors in possible other scenarios.

**Comment by Wilenty** [comment]
Hello,
thank you for the good words!

I will check it and let you know here.

**Comment by Wilenty** [comment]
Fixed the message about missing Icons Theme, and checked on W11 (not the latest) on VM:
![7z2105-x64](https://user-images.githubusercontent.com/61757638/142845301-a066c5d7-e395-44c0-9b8f-7dcdf95a5ce7.png)
it looks that it works correctly.

BTW, it's your topic: https://sourceforge.net/p/sevenzip/discussion/45797/thread/9f670409ab/ ?

Igor said that he not use W11, and I agree with him - it's to early to use new OS creation for production...

**Comment by EgeGurkan** [comment]
thank you very much for fix & test..

yes thats my thread i wanted to share my experience with him...

**Comment by Wilenty** [comment]
Thank you for checking it and reporting it too.
