### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by avanlex** [Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1#5]
Edge Browser, Yandex browser reports about virus and 7Zip reports about it when extracting and cancels it.

Virus Total report:
![image](https://user-images.githubusercontent.com/12039276/162535098-77d812c6-c270-453c-a737-8fa53f37a4df.png)

**Comment by Wilenty** [comment]
Hello,
yes, please look what I wrote there:
![01](https://user-images.githubusercontent.com/61757638/162538047-c353f25e-3789-4e06-be10-3e97ba796603.png)
and there:
![02](https://user-images.githubusercontent.com/61757638/162538082-f843c560-a6bb-4dff-b114-8d3e826912ee.png)
-> https://github.com/Wilenty/7zTC-7-ZIP-Theme-Changer

P.S.
And, please close this issue. :)
