### ISSUE TITLE
7zTM_3_5_2.7z Blocked By Windows Defender

### ISSUE THREAD

**Issue by helmanfrow** [Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1#6]
7-Zip reports no archives found. Windows 10 Defender reports malicious file.

**Comment by Wilenty** [comment]
Hello,
please look what I wrote there: https://github.com/Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1/issues/5#issuecomment-1093400995

This program was abandoned because of that problem with AV detection of AutoIT made programs.

**Comment by helmanfrow** [comment]
Ah, okay, I missed that, thanks.
